### ISSUE TITLE
Distinguish BOPZ and new locations

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#12]
Als IGJ wil ik onderscheid kunnen zien tussen locaties uit de BOPZ en nieuwe locaties.

**Comment by erikvullings** [comment]
Importer needs to add that label too.

**Comment by robw001** [comment]
Update: We denken nu aan een extra veld in de import, voorstel label voor de csv: "isbopz". Nog niet uitgewerkt hoe dat in de applicatie cq. een export zichtbaar moet zijn.

Dit zorgt ervoor dat er (bijvoorbeeld) op 02-jan-2020 nog een wijziging in de BOPZ lijst van 28-12-2019 kan worden verwerkt.

**Comment by erikvullings** [comment]
Toegepast - dit wordt niet beschikbaar gemaakt in de CSV, maar zit wel in de REST interface.
