### ISSUE TITLE
KvK for new locations

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#13]
Als zorgaanbieder wil ik bij het registreren van een nieuwe locatie het KvK vestigingsnummer kunnen gebruiken om automatisch de adresgegevens op te halen.

1. Dus zoek op KvK
2. Edit
3. Nieuwe locatie
4. Enter KvK vestigingsnummer
5. Gegevens worden bij het KvK opgevraagd en ingevuld.

**Comment by robw001** [comment]
Welke "de gegevens" haal je op?

Volgens mij zijn dat:
- Statutaire naam van de instelling (dit is de NHR term, voor locatieregister: Zorgaanbieder) behorend bij het KvK nummer
- Adres (straatnaam, huisnummer, huisnrtoevoeging, postcode, woonplaatsnaam) van de _hoofdvestiging_ van de instelling
- Rechtsvorm van de instelling
