### ISSUE TITLE
PDOK for new locations

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#14]
Als zorgaanbieder wil ik bij het registreren van een nieuwe locatie op basis van postcode en huisnummer automatisch de adresgegevens op laten halen, om fouten te voorkomen.

Dus enter postcode en huisnummer, en de locatiegegevens worden automatisch aangemaakt.

**Comment by robw001** [comment]
Vraag: zou je ook huisnummertoevoeging mee moeten geven (de 'a' van '12a')? Wat zegt de PDOK spec hierover?

Ook: hoe dan de toevoeging in te vullen? Als apart ('12', 'a') veld of als onderdeel van het huisnummer ('12a')?
