### ISSUE TITLE
Save work in progress

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#17]
Als zorgaanbieder wil ik dat mijn wijzigingen tussentijds worden bewaard, zodat ik bij een storing niet opnieuw hoef te beginnen.

**Comment by erikvullings** [comment]
Iedere edit wordt meteen opgeslagen en gesaved, zonder expliciete save opdracht te geven. Dit omdat het vaak voorkwam dat mensen hun aanpassingen vergaten op te slaan, en ze zo verloren gingen.

**Comment by robw001** [comment]
Is er een nuttig verschil tussen "data entry", "correctie" en "formele wijziging"?

Het lijkt me nuttig om iets dieper in een transactiemechanisme te duiken. Is het mogelijk om bv. een edit te stagen en in een latere stap een overwrite van het betreffende 'master' record te doen?

**Comment by erikvullings** [comment]
Het transactiemechanisme is simpel: iedere wijziging wordt meteen
doorgevoerd en opgeslagen. Dan verlies je je wijzigingen niet.
Kan het efficiënter: jazeker, maar niet out-of-the-box, en dit valt mijns
inziens meer onder optimalisaties voor later.
