### ISSUE TITLE
Incident and problem resolution

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#22]
Als beheerder wil ik issues t.a.v. de werking van het register kunnen ontvangen, om incidenten en problems op te kunnen laten lossen.

**Comment by erikvullings** [comment]
Voorstel: neem een info@dwangindezorg.nl mailadres op in de manual.

**Comment by robw001** [comment]
Er is een officieel mailadres gekoppeld aan dwangindezorg.nl. Lijkt me beter dan "info@dwangindezorg.nl" Ik weet de precieze naam niet, lijkt op "wvggzwzd@minvws.nl". Ga ik opzoeken.

**Comment by erikvullings** [comment]
Top

**Comment by robw001** [comment]
Het e-mail adres is wvggzwzdwfz@minvws.nl, Paul Bergen is aan het uitzoeken of we erop kunnen aansluiten.

**Comment by erikvullings** [comment]
locatieregister@dwangindezorg.nl
