### ISSUE TITLE
Locaties worden als niet-actief getoond.

### ISSUE THREAD

**Issue by robw001** [erikvullings/dwang-in-de-zorg#35]
Bij commit 6185835:

Alle locaties in de initiele import hebben een ingangsdatum 31-dec-2019 en geen einddatum. De ingangsdatum wordt getoond, met daarboven de tekst "Deze locatie is momenteel niet actief. Specificeer een ingangsdatum om hem te activeren".

Verwacht: als er een ingangsdatum is en geen einddatum geeft de tekst weer dat de locatie "actief" is.

**Comment by erikvullings** [comment]
Dat gebeurt ook wanneer de ingangsdatum in het verleden ligt. 31 december is echter in de toekomst, dus dan is hij nu niet actief. Indien dit niet het gewenste gedrag is, open hem opnieuw.
