### ISSUE TITLE
Validatie is wenselijk bij het aanmaken van nieuwe zorgaanbieders

### ISSUE THREAD

**Issue by robw001** [erikvullings/dwang-in-de-zorg#38]
Scenario: ik maak een account aan in keycloak, vervolgens maak ik een zorgaanbieder obv. een bestaand KvK nr. Ik ben daarna eigenaar van dat document. Ik kan me zo de rechten toe-eigenen voor een willekeurige zorgaanbieder.

Dit kun je afdichten door zelfgemaakte accounts geen rechten te geven, heb nog niet goed beeld of / welke verdere beperkingen je daarmee introduceert elders in de applicatie.

Wat hier het best mee te doen?

**Comment by erikvullings** [comment]
Je kunt inderdaad een zorgaanbieder (of een locatie) meerdere malen registreren (je kunt daarmee niet een bestaande zorgaanbieder overnemen, maar wel een nieuwe versie aanmaken). Als je dat wil tegengaan, dan moet je alle zorgaanbieders manueel registreren en hun eerste account geven in een separaat proces. 
In de toekomst gebruik je eHerkenning, dus dan zal dit probleem er niet meer zijn.
