### ISSUE TITLE
Assign edit rights to others

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#6]
Als zorgaanbieder wil ik dat alleen aangewezen vertegenwoordigers van mijn instelling mutaties kunnen doorvoeren op mijn locaties.

**Comment by robw001** [comment]
Dit is niet helemaal hetzelfde als #16.

- De eerste uitgegeven userid voor een zorgaanbieder moet gevalideerd zijn (processtap, naar verwachting buiten de applicatie). De hoe en wat van deze processtap is nog niet duidelijk: hoe de "eerste" account te valideren.
- De eerst uitgegeven userid voor een zorgaanbieder kan rechten hebben om andere accounts aan te maken of bestaande accounts te machtigen voor de betreffende zorgaanbieder.

Er zit in mijn beleving een limiet aan de machtigingen: je kunt maar voor één zorgaanbieder gemachtigd zijn als 'editor'.

**Comment by erikvullings** [comment]
Ik snap het. Wat betreft de eerste autorisatie, je kunt of alle gebruikers aanmaken en ze een initieel wachtwoord toewijzen (moet uitgezocht worden, want wie zijn die eerste gebruikers, en welke emails hebben zij), of je laat ze zelf hun account aanmaken en linken met een KvK, en je fixt de accounts handmatig waar het misgaat.
