### ISSUE TITLE
(P1) De applicatie maakt lege zorgaanbieder documenten aan

### ISSUE THREAD

**Issue by robw001** [erikvullings/dwang-in-de-zorg#63]
(Prio 1, leidt tot vervuiling in het register)

Het zou niet mogelijk moeten zijn om een zorgaanbieder aan te maken anders dan met het KVK nummer behorend bij de useraccount. Visueel lijkt de knop niet te functioneren.

De applicatie maakt echter een "leeg" ZA document aangemaakt als je de knop aanklikt. Die ZA is vervolgens zichtbaar in de lijst zonder naam en met het betreffende userID als KVKnr.

Verwachting (een van de volgende): 1) knop is niet zichtbaar als je geen recht hebt om een ZA aan te maken, 2) er wordt geen "leeg" ZA document aangemaakt in de database.

**Comment by erikvullings** [comment]
Wie maakt deze dingen aan? Een admin (Marleen, Iso, Reinier, etc. zijn allemaal admin)? Of iemand met een kvk account?

Ik heb de implementatie wel aangepast, maar een admin kan nog steeds de DB vervuilen,

**Comment by robw001** [comment]
Dit zijn inderdaad de admin accounts.

Er is een workaround: verwijder de registratie terwijl het scherm nog open staat.

Wat heb je gewijzigd aan de implementatie?

PS: het lijkt nu alsof het document direct in de database wordt aangemaakt en daarna met de ingevulde gegevens wordt gewijzigd.
