### ISSUE TITLE
(P1) Locatiegegevens van de zorgaanbieder zijn niet wijzigbaar.

### ISSUE THREAD

**Issue by robw001** [erikvullings/dwang-in-de-zorg#68]
P1: leidt tot incomplete registraties in het register.

Voor de zorgaanbieder met KVKnr 09119500 (Stichting Zorgrécidence Regina) worden geen adresgegevens opgehaald uit het NHR. Het is niet mogelijk om ze handmatig toe te voegen.

Stichting Zorgrécidence Regina heeft geen hoofdvestiging geregistreerd in het NHR. Ik verwacht dat dit vaker zal voorkomen bij kleine zorgaanbieders. We hebben daarbij voor nu geen verplichting ingesteld om eerst de KVK registratie in orde te maken alvorens opname in het locatieregister toe te staan.

Verwachting: adresgegevens zijn handmatig op te voeren in het geval dat er geen adresgegevens voor de hoofdvestiging uit het NHR kunnen worden opgehaald voor een zorgaanbieder.

**Comment by erikvullings** [comment]
Inmiddels aangepast en opgelost
