### ISSUE TITLE
Publish record explicitly

### ISSUE THREAD

**Issue by erikvullings** [erikvullings/dwang-in-de-zorg#9]
Als zorgaanbieder wil ik mijn gegevens kunnen controleren voordat deze gepubliceerd worden, om eventueel fouten te voorkomen.

**Comment by robw001** [comment]
Heeft dit relatie met #17? (die had je al gesloten)

Is het mogelijk om bv. een edit te 'stagen' en in een latere stap een overwrite van het betreffende 'master' record te doen?

**Comment by erikvullings** [comment]
Ja, dat is mogelijk, maar dan vergeten mensen vaak weer te saven, bv als de browser tab wordt afgesloten. Vandaar dat je meestal een impliciete save ziet.
